import CoffeeChat from "@/components/CoffeeChat/CoffeeChat";
import HeroBanner from "@/components/HeroBanner/HeroBanner";
import About from "@/components/Home/About/About";
import Features from "@/components/Home/Features/Features";
import Layout from "@/components/Layout/Layout";
import SEO from "@/components/SEO/SEO";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Antonio Vidakovic</title>
      </Head>
      <Layout>
          <HeroBanner />
          <About />
          <Features />
          <CoffeeChat />
          <SEO />
      </Layout>
    </>
  );
}
